language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-performance-test
  api_key:
    secure: HP0w1RE8QuxrUyA6+nfU9jwqHNrjM2C97ghrLBfPcjZvANPoMZEFZpj1VqZTXW3wqj1DcL1tT+2SbkKaxSU3Ep3I0WgImOLgrTzlTIHqc0cpSYrWXpgAunzmQo56w7Sh92/ja1IqXv41winPn2ZwJamjR5UWCjssoQ6ZnoDVq1huRfx0dhthY/YXQJ1MMPbxXJXWNpe0Ksh9VS0iwKp4pJ4O8jF+iJSw9Pwwnq4GkAGVc0PxFHAH4re+o587zpWpmxw2EaF2/Ra1/fLFCiEywux9ZAE6lxETk3gYrvkHw5H5WVxqc1vgsxAD6dSx/8+bhfVZQ0agX+eTSO7/gjQgqokqRE1k58pUvHUbttGiP1WMtmEWG5+CogyHJ8rbSTa6HCMDqSXIJzVnJrJZa19Zq0zQp0yt7q3bpJ+Gz9ZLfU5qoibi15TahTORlI7HAzt0JA+odHiqQgyS80MgmFHHuGUfEkKV9QfSwz5tD5+lE1b87e8MoAhmSiN3jV+wATl+lcccW1/DaipEE/ODW4pLRmjc9sts2RrjAtHQrISAq/4Iqq/rBfKD0JkE5ghSi6+i4ohDz1TT0pNfnvO2rfm5STf7J0UamPx/W+MlNgaeIG7ZbAtwTrxDDEFTQOK76VL1yfl9A8KtGbnvZmKWUvQpc81npdnNE5g9F2OvKh8z4Is=
  on:
    repo: degreeproject/vue-performance-test
    branch: master
