language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-performance-test
  api_key:
    secure: JJ1HyKeMPRoQRz0cofHg/K+UKBsmliy2z4yS2IL1N+1CqF1us12z8mvHOnooiL7esQ1IlZG7rZgFgIq9cNbT2FS2YB6OxDu7pDoRSZd+4E7ntzbyyWiFXBZFScdXYlqCjn28ncaKw1BV+HCMacjwcRtADF6Z4B/PisTE9ljpX9UfulTmFVtdsfjmNSD02vFwqgTLlPSTeB1U3kT3FCzYROkKKA0IKbQs4NIi1Go1zSan789hYGY/jRY3LZiqx/VCD0go6WUe+GRKoCuxxf8pqeB+kda60HboyZdxEeuLN4wmeDe0zDl79lsIJ3VviFC5UdR1FFbT37gfjV5aJHJ5KAXVtwQXtLQz0EW5Z1sKbx0SEDtKyV+XSG5J0GjCEA2a5R5YxohP+JoucdM3CN+KzYeTuJ5rqT/5ic9VyCNdCmYvJ3J5SJP+oSrQwpQkEoBYTsotSnfmSyyG+cZccy4WOSXjVl2KAKSV0T5xImkxKs9//2SP+rFo+3cJ5royjrJZ064vdgf34L0YwM1RMBJwYNXeAZBneu44F4KJ8CPXBK+MyqsZh4Fdoc+rUxKFiS3BfCsa5c2rahKdQAAkD1/0n08UE8jVBrYHPAcF2nCXEKpVfsp8U+r8FWv6gZbqPuTWKpx7HjuoIsiM5oMlaiADETcl5d+RM5u0hPCF0TDH1uA=
  on:
    repo: degreeproject/vue-performance-test
    branch: master
