language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-performance-test
  api_key:
    secure: XCe8mfKyXClCRZJhHLEIdHcdmzgE+Cb/koZ4MMVestv2hK2ki6Uykl1aHY/ktuW8ZBYOD4xj6lh4uxgo/TqlAm/xpT9zZtwzP7Pb/S3JrtH1qSD61ALZE850Vf2w+IOCY2ogCMxUsHTRR/MyIyfvU7gKJjBhE+zvdclhR+tAycgeeJIUPjfrz4AhKiNTL3acLAnSh+u2JDiU//pEJVbjn2jwa/S6MK0nYYUpOidy7AoCFnBnP0B0eEaQ/KjWXhqGZSsXTXpw+Koz67SAbQtEGH/OhYuBd/Bd1G9JuFIDsxrOlSYKLnLmy/KZnf+08BrQnKu96v8hoCWSdvyFmdQ8I9aXDWbhyMjCr6NXnfFQ+0Q97t4eGaWrdY+XZ8X9Y2ZBVCG5jV6f1yUct4iEAvZPsRqVA0FNTtxaX9K9Oa4LVcEV/wUFMh9dAw5+CBpveLufp4XUjJMt75gFXxNHeCnnSfxKV2vfqf1h9Zni7TE64zIvqZZ64ujg1MJO2clVpSGyWcX4KwZVmFndznn/N+7CvfVOIZDMYndiz3gtkaSTjlMmdJ42WvNvTlrynmqkMW72vV1ODUSStwC2Y6SGedf+IBhUrHmJHzsO3hBZywJwj39k+QTVP4RVyHpyucOgzk8+uXN4cc2isdNsE1ylFQqsbP2zeUyVFST3+LDv/gfrlVU=
  on:
    repo: degreeproject/vue-performance-test
    branch: master
